apiVersion: v1
kind: Service
metadata:
  name: climate-dao-event-listener
  namespace: climatedao
  labels:
    app: climate-dao-event-listener
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8002
      protocol: TCP
  selector:
    app: climate-dao-event-listener


  
