apiVersion: v1
kind: Service
metadata:
  name: climate-dao-zokrates-worker
  namespace: climatedao
  labels:
    app: climate-dao-zokrates-worker
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8001
      protocol: TCP
  selector:
    app: climate-dao-zokrates-worker
  
