kubectl create secret generic climate-secrets \
  --from-literal=az-keyvault-url=https://uksdiac****.vault.azure.net/ \
  --from-literal=az-tenant-id=5b973f99-77df-4beb-b27d-***** \
  --from-literal=az-client-id=f5cf0b59-efd9-499b-a9d3-***** \
  --from-literal=az-client-secret=~.DEiAW6-C0mwsu-*****- \
  --from-literal=enc-secret=0xd18f22c4c73847502816bfae8364ec29ce06f6161d85cc3edd2dceda50f2dc \
  --from-literal=token-secret=this-is-a-secret-value-with-at-least-32-characters \
  --from-literal=mongo-url='mongodb://uksdiac00gcdb01:MPuOGtZ0Ts4elwapi8gCYZhb*****rmWMO1NT9TRaqow5JZH8AhASEdZFegvOFA==@uksdiac00gcdb01.documents.azure.com:10255/climatedao?ssl=true&replicaSet=globaldb' \
  --from-literal=redis-url='redis://my-release-redis-master.climatedao.svc.cluster.local:6379?password=2vnpYYzFKD' \
  --from-literal=redis-url-host='my-release-redis-master.climatedao.svc.cluster.local' \
  --from-literal=redis-url-port='6379' \
  --from-literal=redis-url-password='2vnpYYzFKD' \
  --from-literal=acuantCallbackPassword=climate \
  --from-literal=idmaApiUserName='33c6abee-bf4d-4451-b8ed-*****' \
  --from-literal=idmaApiPassword=b862b39fc3354ff67202faebf7a6039***** -n climatedao