apiVersion: v1
kind: Service
metadata:
  name: climate-dao-api
  namespace: climatedao
  labels:
    app: climate-dao-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: climate-dao-api


  
