apiVersion: apps/v1
kind: Deployment
metadata :
  name: climate-dao-ui
  namespace: climatedao
  labels:
    app: climate-dao-ui
spec:
  selector:
    matchLabels:
      app: climate-dao-ui
  replicas: 1
  template:
    metadata:
      labels: 
        app: climate-dao-ui
    spec:
      containers:
        - name: climate-dao-ui
          image: ghcr.io/eyblockchain/climate-dao-ui:latest
          resources:
            requests:
              memory: "1G"
              cpu: "1"
            limits:
              memory: "2G"
              cpu: "2"
          env:
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: climate-secrets
                  key: token-secret
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
            initialDelaySeconds: 30
          ports:
            - containerPort: 3000
              protocol: TCP
          securityContext:
            runAsUser: 1000
      imagePullSecrets:
        - name: climatedaoregistry
      terminationGracePeriodSeconds: 90
  