apiVersion: v1
kind: Service
metadata:
  name: climate-dao-ui
  namespace: climatedao
  labels:
    app: climate-dao-ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: climate-dao-ui