name: Development Workflow

on:
  pull_request:
      branches:
        - master
      paths:
        - 'packages/ui/**'
        - 'packages/api/**'
        - 'packages/zokrates-worker/**'
        - 'packages/event-listener/**'

jobs:
  DeployOnDev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout action
        uses: actions/checkout@v1

      - name: Set Variables
        id: vars
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
      - uses: dorny/paths-filter@v2
        id: should_re_deploy
        with:
          base: ${{ steps.vars.outputs.short_ref }}
          filters: |
            api:
              - 'packages/api/**'
            ui:
              - 'packages/ui/**'
            zokratesworker:
              - 'packages/zokrates-worker/**'
            eventlistener:
              - 'packages/event-listener/**'
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: validate before release
        run: |
          npm ci --no-save
          npm run lint
        env:
          SKIP_PREFLIGHT_CHECK: true
          CI: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ui
        if: steps.should_re_deploy.outputs.ui == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./prod.ui.Dockerfile
      
      - name: Build api
        if: steps.should_re_deploy.outputs.api == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./prod.api.Dockerfile

      - name: Build zokrates worker
        if: steps.should_re_deploy.outputs.zokratesworker == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./prod.zokrates.Dockerfile
      
      - name: Build event listener
        if: steps.should_re_deploy.outputs.eventlistener == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./prod.listener.Dockerfile
